name: Github Pages
run-name: GithubPages

on:
  push:
    branches: ["main"]

concurrency:
  group: "githubpages"
  cancel-in-progress: true

jobs:
  githubpages:
    name: Github Pages
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install npm packages
        run: npm ci --force

      - name: Setup variables
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
